"""full

Revision ID: 2d6440e769ba
Revises: ebff9bb618e7
Create Date: 2023-04-04 17:33:29.961035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6440e769ba'
down_revision = 'ebff9bb618e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('phn_number', sa.Integer(), nullable=True))
    op.add_column('Employees', sa.Column('hobbies', sa.String(), nullable=True))
    op.add_column('Employees', sa.Column('experiance', sa.Float(), nullable=True))
    op.add_column('New Employees', sa.Column('phn_number', sa.Integer(), nullable=True))
    op.add_column('New Employees', sa.Column('security_q', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'New Employees', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'New Employees', type_='unique')
    op.drop_column('New Employees', 'security_q')
    op.drop_column('New Employees', 'phn_number')
    op.drop_column('Employees', 'experiance')
    op.drop_column('Employees', 'hobbies')
    op.drop_column('Employees', 'phn_number')
    # ### end Alembic commands ###
