"""Complete

Revision ID: 3f9f5b72ef8f
Revises: e8f3fd6b8068
Create Date: 2023-04-04 21:14:25.332261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9f5b72ef8f'
down_revision = 'e8f3fd6b8068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
