"""Complete

Revision ID: 4a5ab9823dae
Revises: 51d14529e9fd
Create Date: 2023-04-06 01:36:39.242617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5ab9823dae'
down_revision = '51d14529e9fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('security_q', sa.String(), nullable=True))
    op.add_column('Employees', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('New Employees', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('New Employees', 'gender')
    op.drop_column('Employees', 'gender')
    op.drop_column('Employees', 'security_q')
    # ### end Alembic commands ###
