"""Is Ok

Revision ID: 51d14529e9fd
Revises: 9210b0876fd9
Create Date: 2023-04-04 21:20:30.241102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d14529e9fd'
down_revision = '9210b0876fd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('Employees', 'phn_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('phn_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Employees', 'phone_number')
    # ### end Alembic commands ###
