"""full

Revision ID: 7620c781ab27
Revises: 5766861361d8
Create Date: 2023-04-04 20:40:29.782743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7620c781ab27'
down_revision = '5766861361d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('bravo', sa.Integer(), nullable=True))
    op.add_column('Employees', sa.Column('raises', sa.Integer(), nullable=True))
    op.add_column('Employees', sa.Column('trumpet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Employees', 'trumpet')
    op.drop_column('Employees', 'raises')
    op.drop_column('Employees', 'bravo')
    # ### end Alembic commands ###
