"""full

Revision ID: 828e4b78f132
Revises: 7620c781ab27
Create Date: 2023-04-04 20:58:18.709091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828e4b78f132'
down_revision = '7620c781ab27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Employees', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
