"""okk

Revision ID: 9210b0876fd9
Revises: 3f9f5b72ef8f
Create Date: 2023-04-04 21:16:10.573494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9210b0876fd9'
down_revision = '3f9f5b72ef8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
