"""Complete

Revision ID: ac3b99794216
Revises: 4a5ab9823dae
Create Date: 2023-04-06 01:48:11.129437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3b99794216'
down_revision = '4a5ab9823dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('New Employees', sa.Column('stack', sa.String(), nullable=True))
    op.drop_column('New Employees', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('New Employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('New Employees', 'stack')
    # ### end Alembic commands ###
