"""full

Revision ID: e8f3fd6b8068
Revises: 828e4b78f132
Create Date: 2023-04-04 21:08:35.198127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f3fd6b8068'
down_revision = '828e4b78f132'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
